2024-09-20 14:04:55,808 , 87 , WARNING , Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\tests_12_4.py", line 79, in test_run
    runner_1 = Runner({1, 1})
               ^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\tests_12_4.py", line 11, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано set
2024-09-20 14:04:55,810 , 74 , WARNING , Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\tests_12_4.py", line 63, in test_walk
    walker_1 = Runner('J. Walker', -5)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\PycharmProjects\tests_12_4.py", line 16, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
